jwt:
  secret: veryverysecret
  expire.hours: 24

server:
  port: 8080
  servlet.context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/databucket
    username: databucket_user
    password: databucket_user
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
